### ISSUE TITLE
Error win7 python3.7

### ISSUE THREAD

**Issue by Piskuliki0723** [naufraghi/tinyaes-py#17]
https://github.com/pyinstaller/pyinstaller/issues/5180
In Pyinstaller, the library is declared in the documentation, but this only works on Linux (checked).  On Windows I installed VS2019 and a bunch of different C ++ addons, but that doesn't go on Windows 7 with Python 3.7.  The guys from Pyinstaller are very touchy, instead of help, referral.  Any ideas on how to make this work?

These errors are also very similar to dead "pycrypto".
https://user-images.githubusercontent.com/61133932/93550457-18740280-f974-11ea-906f-60b3ac41a520.jpg

**Comment by naufraghi** [comment]
I partly understand the response, the encryption support is a best-effort feature for PyInstaller.

The strange fact is that the CI runs on windows too, perhaps not on Windows 7 (logs are gone). I have used `tinyaes-py` in the past on Windows 7 too, but with Python 2.7 only.

Is the binary `wheel` not matching your platform? 

If you really need to build it, you can have a look at what the CI is doing and try to replicate the workflow locally.

Beside that, I may accept contributions to support deprecated platforms (documentation or minimal source changes), but I wouldn't really want to invest my time to solve this problem, sorry.

https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information
> Support for Windows 7 has ended
>
> After 10 years, support for Windows 7 ended on January 14, 2020. We know change can be difficult, so we are here to help you with recommendations for what to do next and to answer questions about end of support.

**Comment by naufraghi** [comment]
Can this thread help? https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory

**Comment by naufraghi** [comment]
A assume the issue was solved or at least stale, closing.
