### ISSUE TITLE
Package a "tinyaes-1.0.1-cp39-cp39-win_amd64.whl" for python3.9

### ISSUE THREAD

**Issue by wordhui** [naufraghi/tinyaes-py#20]
> Python3.9 installation of this software requires "Microsoft Visual C++ 14.0"
Installing "Microsoft Visual C++ 14.0" takes up too much disk space, hope to upload "tinyaes-1.0.1-cp39-cp39-win_amd64.whl" to solve the troublesome installation problem
```shell
running bdist_wheel
  running build
  running build_ext
  building 'tinyaes' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for tinyaes
```

**Comment by naufraghi** [comment]
I have an half baked PR to support more platforms, are you willing to test a pre-release?

**Comment by wordhui** [comment]
Thank you
Because my usage scenario is relatively simple, I cannot bring good test results here
Mainly use it in pyinstaller
I used it this time and performed perfectly in Python3.9

**Comment by johnthagen** [comment]
@naufraghi Any updates on Python 3.9 support?

**Comment by naufraghi** [comment]
I think I can consider `1.0.2rc1` stable enough to be promoted
