### ISSUE TITLE
Installing Shows Error

### ISSUE THREAD

**Issue by Yuvaraja28** [naufraghi/tinyaes-py#25]
I use Windows 10 and installing tinyaes for python3.10.2 shows errors when installing need a fix for this

**Comment by naufraghi** [comment]
The comment seems truncated, can you provide some more detail?

**Comment by Yuvaraja28** [comment]
I'm using Windows10 and am having Python3.10.2 in this Building wheels for tinyaes Fails and shows errors, and that Error log Image is here can you fix it?
![image](https://user-images.githubusercontent.com/64340067/151700395-1ccf7ca5-a5f5-4661-bf38-32de75d4c9c0.png)

**Comment by Yuvaraja28** [comment]
Latest PIP[22.0] Error Log with detailed view
![image](https://user-images.githubusercontent.com/64340067/151713880-8dad89da-46cc-4b05-9b70-b7f1a756ef65.png)

**Comment by naufraghi** [comment]
Oh, yes, I forgot to release a final 1.0.3 with Python 3.10 support, meanwhile you can use the pre-release `pip install tinyaes==1.0.3rc1`.

Beside that, the error is "Microsoft Visual C++ 14.0 or greater required." In general if you'd like to install packages that are not pure Python and are not offering a binary wheel for your platform / version of Python you may need a compiler.

I suggest you to follow the link and install the suggested build tools, you may need them in the future.

**Comment by Yuvaraja28** [comment]
But as am running with Limited data i cant install all the Build tool Binary Files so can you Release it as quick as possible?

**Comment by naufraghi** [comment]
Sorry for the delay @Yuvaraja28, just released 1.0.3 with Python 3.10 wheels.
