### ISSUE TITLE
Install of tinyaes 1.0.3 fails on Python 3.11

### ISSUE THREAD

**Issue by mark-ramsey-ri** [naufraghi/tinyaes-py#31]
Installing tinyaes fails on Windows 10 with the latest release of Python:

pip3 install tinyaes
Collecting tinyaes
  Using cached tinyaes-1.0.3.tar.gz (42 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: tinyaes
  Building wheel for tinyaes (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for tinyaes (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'tinyaes' extension
      creating build
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\tiny-AES-c
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Itiny-AES-c/ -IC:\Users\Mark\AppData\Local\Programs\Python\Python311\include -IC:\Users\Mark\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.17763.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.17763.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.17763.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.17763.0\\cppwinrt" /Tctiny-AES-c/aes.c /Fobuild\temp.win-amd64-cpython-311\Release\tiny-AES-c/aes.obj
      aes.c
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Itiny-AES-c/ -IC:\Users\Mark\AppData\Local\Programs\Python\Python311\include -IC:\Users\Mark\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.17763.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.17763.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.17763.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.17763.0\\cppwinrt" /Tctinyaes.c /Fobuild\temp.win-amd64-cpython-311\Release\tinyaes.obj
      tinyaes.c
      tinyaes.c(3601): error C2037: left of 'f_lineno' specifies undefined struct/union '_frame'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinyaes
Failed to build tinyaes
ERROR: Could not build wheels for tinyaes, which is required to install pyproject.toml-based projects

**Comment by gcartlidge** [comment]
Same here, the specific:

tinyaes.c(3601): error C2037: left of 'f_lineno' specifies undefined struct/union '_frame'

comes up too, I'm using Build tools 14.33.31629

**Comment by gcartlidge** [comment]
The quickest way to fix this on your installation will be to clone the entire repo, cd into the tinyaes-py folder, then run the 'python setup install' command in cmd

This runs through manual installation and the tinyaes.c source gets generated fine. So not a problem with the code, more just of the installation :) This works perfectly fine on my setup.

**Comment by php737** [comment]
How to operate I won't

**Comment by gcartlidge** [comment]
The wheel file for win_amd64 cp311 is below, you can install this with pip by using the file instead of package name:

pip install "C:\Users\g\Documents\GitHub\tinyaes-py\dist\tinyaes-1.0.3-cp311-cp311-win_amd64.whl"

for example, just change it to where you download.

https://we.tl/t-zPC6cFVuMg

**Comment by php737** [comment]
It has been solved perfectly! Thank you very much !  
![f8f9a068fcff33dd8867706e01938e2](https://user-images.githubusercontent.com/31496660/199460859-3926dbc4-e94b-4d54-88f8-5e33ab5e7516.jpg)

**Comment by naufraghi** [comment]
Thank @gcartlidge for the support!

The official wheel should be ready soon.
