### ISSUE TITLE
Prepare for Python 3.13

### ISSUE THREAD

**Issue by naufraghi** [naufraghi/tinyaes-py#46]
- drop Python 2.7, 3.6 and 3.7 (support Python 3.8+)
- upgrade from windows-2019 to 2020
- upgrade from ubuntu-20.04 to 22.04
- upgrade from macos-11 to 13 and 14
- update actions to the latest version
- remove `x86_64` and `arm64` and keep only `universal2` for macos (follow-up from https://github.com/naufraghi/tinyaes-py/pull/45#discussion_r1715630558)

See #45

**Comment by adehad** [comment]
just checking in, if anything is blocking this?

**Comment by naufraghi** [comment]
Not really, just other duties. I'll try to launch a pre today and later a final

**Comment by naufraghi** [comment]
Done in #51
