### ISSUE TITLE
Include pre-built binaries on pip

### ISSUE THREAD

**Issue by Legorooj** [naufraghi/tinyaes-py#5]
One problem with this library:

It installs from source - which means that you have to compile it yourself. Would you be willing to setup a process which builds for multiple platforms and uploads wheels to PyPI?

**Comment by naufraghi** [comment]
I'll have a look, it should be possible to publish from the CI directly to avoid any human error.

**Comment by Legorooj** [comment]
@naufraghi I haven't worked with GitHub actions before, but it is possible on other providers - and GitHub actions should do it.
