### ISSUE TITLE
Update license for PyInstaller compatibility

### ISSUE THREAD

**Issue by Legorooj** [naufraghi/tinyaes-py#6]
One problem with your current license (MPL-2) is that it doesn't allow people using the library to distribute it closed source. That means that PyInstaller users can't distribute their closed-source python apps legally. Could you switch to another license, like MIT, Unlicense, or a custom one based off the MPL-2 that allows this?

**Comment by naufraghi** [comment]
It should under the chapter «3.3. Distribution of a Larger Work» https://www.mozilla.org/en-US/MPL/2.0/ but I'll switch/double license to something else because the rules of MPL-2.0 are a bit unclear.

**Comment by Legorooj** [comment]
@naufraghi that chapter is confusing. I might suggest a slightly modified version of the GPL like PyInstaller has? Allowing the end user to use the library in closed source apps provided that they state that they use it and don't modify it?
