### ISSUE TITLE
Switch your devevlopment workflow

### ISSUE THREAD

**Issue by Legorooj** [naufraghi/tinyaes-py#7]
If you switch to a workflow similar to pyinstaller's, you can have two branches, `dev` and `master`. Master houses stable releases, and is only pushed to when you do a release. Then you can have CI that does testing on the `dev` branch, and *CD* (continuous deployment/delivery) on the master branch that builds wheels and uploads them to PyPI?

Related to #5.

**Comment by naufraghi** [comment]
This should not be a problem for PyInstaller: the packages should be referred using official PyPI releases.

I have not yet defined a development method, but the PyInstaller one is an option I'll evaluate.

**Comment by Legorooj** [comment]
@naufraghi this one isn't actually related to PyInstaller too much. This one I just think is sensible.

**Comment by naufraghi** [comment]
I think the `develop` / `master` approach is sensible with a bigger project.

For this little wrapper I prefer KISS and, given I don't think I'll have many revolutions, I'll use master for the current release and create a `release/1` branch for eventual back-ports if I'll ever need to move the master to version 2.

I'm closing this issue and I'll evaluate a more complex structure when some problem will occur, keeping your suggestion in mind @Legorooj .
